services:
  bot:
    build: .
    command: python3 app.py
    volumes:
      - .:/app
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure:3

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: